### ISSUE TITLE
Please fix: unit test failure

### ISSUE THREAD

**Issue by ruiwang2uber** [facebookresearch/Horizon#127]
======================================================================
FAIL: test_trainer_maxq (ml.rl.test.constant_reward.test_constant_reward.TestConstantReward)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Horizon/ml/rl/test/constant_reward/test_constant_reward.py", line 93, in test_trainer_maxq
    trainer = self._train(maxq_parameters, env)
  File "/home/Horizon/ml/rl/test/constant_reward/test_constant_reward.py", line 30, in _train
    trainer = create_dqn_trainer_from_params(model_params, env.normalization)
  File "/home/Horizon/ml/rl/workflow/transitional.py", line 97, in create_dqn_trainer_from_params
    metrics_to_score=metrics_to_score,
  File "/home/Horizon/ml/rl/training/dqn_trainer.py", line 44, in __init__
    actions=parameters.actions,
  File "/home/Horizon/ml/rl/training/rl_trainer_pytorch.py", line 74, in __init__
    self.loss_reporter = LossReporter(actions)
  File "/home/Horizon/ml/rl/training/loss_reporter.py", line 183, in __init__
    BatchStats.add_custom_scalars(action_names)
  File "/home/Horizon/ml/rl/training/loss_reporter.py", line 104, in add_custom_scalars
    title="model",
  File "/home/Horizon/ml/rl/tensorboardX.py", line 87, in add_custom_scalars_multilinechart
    ), "Title ({}) is already in category ({})".format(title, category)
AssertionError: Title (model) is already in category (propensities)

----------------------------------------------------------------------

I follow the Docker installation and the error came at the last step when i ran the unit test.

**Comment by econti** [comment]
Fixed in https://github.com/facebookresearch/Horizon/commit/95565d6c862818de5ddc336626f8169791a9d7e9
