### ISSUE TITLE
mvn -f preprocessing/pom.xml clean package Failed

### ISSUE THREAD

**Issue by snowzjy** [facebookresearch/Horizon#96]
mvn -f preprocessing/pom.xml clean package 
......

\- two-state-mdp
19/02/20 23:17:09 INFO TimelineTest: Full logs for test case: /tmp/com.facebook.spark.rl.TimelineTest_filter-outliers.log
\- filter-outliers *** FAILED ***
  org.apache.spark.sql.AnalysisException: Undefined function: 'fb_approx_percentile'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.; line 3 pos 28
  at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$15$$anonfun$applyOrElse$50.apply(Analyzer.scala:1216)
  at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$15$$anonfun$applyOrElse$50.apply(Analyzer.scala:1216)
  at org.apache.spark.sql.catalyst.analysis.package$.withPosition(package.scala:53)
  at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$15.applyOrElse(Analyzer.scala:1215)
  at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$15.applyOrElse(Analyzer.scala:1213)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:267)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:267)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:266)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:272)
  ...
Run completed in 20 seconds, 846 milliseconds.
Total number of tests run: 5
Suites: completed 2, aborted 0
Tests: succeeded 4, failed 1, canceled 0, ignored 0, pending 0
*** 1 TEST FAILED ***

**Comment by kittipatv** [comment]
https://github.com/facebookresearch/Horizon/pull/97 should fix the issue. Could you confirm?

**Comment by kittipatv** [comment]
This should be fixed in master. Please reopen if you still experience the issue
